name: Add Label

on:
  issues:
    types: opened

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a/add-label
        with:
          labels: "bug"
